### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by comradekingu** [Ejgouda/Taxasoft-BG#1]
I can't seem to find any license info?
Would expect to find it in a file called COPYING.md

**Comment by mfrasca** [comment]
given the client-server structure of the software, may I suggest you distribute it under the [AGPL license](https://www.gnu.org/licenses/agpl-3.0.en.html)?

**Comment by mfrasca** [comment]
(I have followed the github style: "license.txt" rather than the GNU logic "copying".  no particular reason, but because we are in github.)

**Comment by Ejgouda** [comment]
I have added the AGNU license, but do not see where it went.

**Comment by mfrasca** [comment]
consider merging my pull request, it contains the `LICENSE.txt` file

**Comment by comradekingu** [comment]
@Ejgouda It is in the add-license-1 branch https://github.com/Ejgouda/Taxasoft-BG/tree/add-license-1

**Comment by Ejgouda** [comment]
I think I already added a license file, can you find it?


Op 29-10-18 om 17:58 schreef Mario Frasca:

**Comment by mfrasca** [comment]
Eric, follow this link, and perform the merge:
https://github.com/Ejgouda/Taxasoft-BG/compare/Ejgouda:master...Ejgouda:add-license-1?expand=1
