### ISSUE TITLE
missing software icon

### ISSUE THREAD

**Issue by mfrasca** [Ejgouda/Taxasoft-BG#2]
I understand this will add nothing to the functionality, but an icon would be nice.
thinking of how software icons work in the outside world, I guess you have to decide your representative colour.  just like red->youtube; dark blue->facebook; light blue->skype, green->whatsapp …
I'm able to lend you a painting hand for the next few weeks, let me know.

**Comment by Ejgouda** [comment]
I will check the whole project and reload all files.

**Comment by mfrasca** [comment]
we added the icon, and I later updated it, to:
![image](https://user-images.githubusercontent.com/122869/57865426-2edbde00-77c3-11e9-8e8e-2f44ceaaf770.png)
