### ISSUE TITLE
call to undefined function simplexml_load_file

### ISSUE THREAD

**Issue by mfrasca** [Ejgouda/Taxasoft-BG#4]
I'm having a look at how to start the published version, (I have apache 2.4.25-3+deb9u, php 7.0.30-0+deb9u1, MySQL 5.8+1.0.2—but have not linked the php sources to any database, for I don't see where/how to indicate my database parameters.)

I meet this `Call to undefined function simplexml_load_file`:
```
[Mon Oct 29 10:57:29.973823 2018] [:error] [pid 29336] [client ::1:40014] PHP Warning:  include(guest.pass.php): failed to open stream: No such file or directory in /home/mario/Local/github/mfrasca/Taxasoft-BG/index1.php on line 6
[Mon Oct 29 10:57:29.973894 2018] [:error] [pid 29336] [client ::1:40014] PHP Warning:  include(): Failed opening 'guest.pass.php' for inclusion (include_path='.:/usr/share/php') in /home/mario/Local/github/mfrasca/Taxasoft-BG/index1.php on line 6
[Mon Oct 29 10:57:29.974004 2018] [:error] [pid 29336] [client ::1:40014] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /home/mario/Local/github/mfrasca/Taxasoft-BG/index1.php:26\nStack trace:\n#0 {main}\n  thrown in /home/mario/Local/github/mfrasca/Taxasoft-BG/index1.php on line 26
```

**Comment by mfrasca** [comment]
in Debian based distributions, there's the depenency from `php-xml`.
it has to be installed, and enabled, as described for example [here](https://stackoverflow.com/a/36407094/78912).
I would document this somewhere, of put in an installation script.

there are further dependencies, also to be documented or automated.
`Call to undefined function mysql_connect`

**Comment by Ejgouda** [comment]
http://php.net/manual/en/function.simplexml-load-file.php

I have to load a new version that has converted from mysql_ functions to msqli_ functions because they are depricated in PHP 7

**Comment by mfrasca** [comment]
4cf577c7fe7e15b202370c43bd63e64cf445a636
