### ISSUE TITLE
ERROR: Addiditional Function file not found: 'taxasoftBGtools.php'

### ISSUE THREAD

**Issue by mfrasca** [Ejgouda/Taxasoft-BG#5]
when starting the software the way it is now in the repository, this is the message I get.

**Comment by Ejgouda** [comment]
what message Mario?


Op 08-11-18 om 20:23 schreef Mario Frasca:

**Comment by mfrasca** [comment]
the one in the subject - title of the issue
`ERROR: Addiditional Function file not found: 'taxasoftBGtools.php'`

**Comment by mfrasca** [comment]
9f39e52315fc7eef7520828c3a170d57e8072da2
